(define (problem clean_table)
    (:domain dining)
    (:requirements :strips :typing)
    (:objects basement - location dining - location kitchen - location outlet_1 - appliance robot_1 - robot table_1 - furniture vacuum_1 - appliance)
    (:init 
        (arm_is_free robot_1) 
        (outlet_at outlet_1 dining) 
        (robot_at robot_1 kitchen) 
        (table_at table_1 dining) 
        (vacuum_at vacuum_1 dining) 
        (vacuum_is_off vacuum_1) 
        (vacuum_is_unplugged vacuum_1)
    )
    (:goal (and (table_is_clean table_1) (vacuum_is_off vacuum_1) (vacuum_is_unplugged vacuum_1) (arm_is_free robot_1)))
)